### ISSUE TITLE
Python 3.12 error?

### ISSUE THREAD

**Issue by zarif98** [abinthomasonline/repopack-py#2]
![image](https://github.com/user-attachments/assets/8884dea5-c724-497f-b121-c00b43487eec)

Seems like a coding error?

**Comment by abinthomasonline** [comment]
@zarif98 Thank you for pointing out! 

Just released a patch to fix this. https://github.com/abinthomasonline/repopack-py/commit/bf136a06d130d40db2b8ef9772a8dfc91eb7f1ce

do `pip install repopack-py --upgrade`
