### ISSUE TITLE
Emojis in files crashes 'packing files' stage

### ISSUE THREAD

**Issue by yunusdemir** [abinthomasonline/repopack-py#3]
Hi there, just started testing repopack-py! 

Some of my files have emoji in them, which made the process crash. After removal of said emojis the command works fine again.

Error (I changed the paths to remove some irrelevant information) :
```shell
`⠙ Packing files...INFO: Total files to process: 6334
⠧ Packing files...ERROR: Error processing files: Error processing file './../password_reset_key_message.txt': Error processing file ./../password_reset_key_message.txt': 'charmap' codec can't decode byte 0x8d in position 144: character maps to <undefined>
✖ Error during packing: File processing error: Error processing file ./../password_reset_key_message.txt': Error processing file ./../password_reset_key_message.txt': 'charmap' codec can't decode byte 0x8d in position 144: character maps to <undefined>
ERROR: File processing error: Error processing file './../password_reset_key_message.txt': Error processing file './../password_reset_key_message.txt': 'charmap' codec can't decode byte 0x8d in position 144: character maps to <undefined>
```

**Comment by abinthomasonline** [comment]
@yunusdemir 
chardet detection is not that accurate it seems, added an option to fallback to utf-8 upon failure.

Just released a new version to fix this bug.  https://github.com/abinthomasonline/repopack-py/commit/06828dbf729191dd896d02c0f1cc0cf196c1ea44 

do `pip install repopack --upgrade`

Thank you for pointing out!
